name: Introducing QM/MM
category: advanced
authors: ""
shortdesc: The course will introduce non-specialists to the use of combined quantum mechanics/molecular mechanics (QM/MM) methods for modelling enzyme-catalysed reaction mechanisms.
longdesc: ""
